version: '3'
services:
  web:
    build: ./nginx
    ports:
    - "80:80"
    volumes:
    - ./src:/var/www/html
    depends_on:
      - php-fpm
      - db
    links:
      - php-fpm
      - db
    networks:
      - my-network
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - my-network
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    ports:
      - "3300:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - my-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
     - my-network
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - my-network
  elasticsearch:
    image: elasticsearch:2.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
    
